permalink: pretty

title: Nídia Trovão
tagline: Website
url: http://nidiatrovao.com
baseurl: "http://nidiatrovao.com"

sass:
  sass_dir: _sass
  style: :compressed
  
pages_list:       
  About: '/about'
  Publications: '/publications'
