permalink: none

title: Nídia Trovão
tagline: Website
url: https://nidiatrovao.com
baseurl: "https://nidiatrovao.com"

sass:
  sass_dir: _sass
  style: :compressed
  
pages_list:       
  About: '/about'
  Publications: '/publications'
